server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
        routes:
          - id: CLIENT-SERVICE
            uri: lb://CLIENT-SERVICE
            predicates:
              - Path=/CLIENT-SERVICE/**
            metadata:
              cors:
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                  - HEAD
                  - TRACE
                  - CONNECT
                allowedHeaders: '*'
                allowCredentials: true
          - id: LOAN-SERVICE
            uri: lb://LOAN-SERVICE
            predicates:
              - Path=/LOAN-SERVICE/**
            metadata:
              cors:
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                  - HEAD
                  - TRACE
                  - CONNECT
                allowedHeaders: '*'
                allowCredentials: true
          - id: CONTRACT-SERVICE
            uri: lb://CONTRACT-SERVICE
            predicates:
              - Path=/CONTRACT-SERVICE/**
            metadata:
              cors:
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                  - HEAD
                  - TRACE
                  - CONNECT
              allowedHeaders: '*'
              allowCredentials: true
          - id: AUTH-SERVICE
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/AUTH-SERVICE/**
            metadata:
              cors:
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                  - HEAD
                  - TRACE
                  - CONNECT
                allowedHeaders: '*'
                allowCredentials: true
          - id: ACCOUNT-SERVICE
            uri: lb://ACCOUNT-SERVICE
            predicates:
              - Path=/ACCOUNT-SERVICE/**
            metadata:
              cors:
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                  - HEAD
                  - TRACE
                  - CONNECT
                allowedHeaders: '*'
                allowCredentials: true
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/AppCC-realm
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway
        display-name: Gateway
      - url: /CLIENT-SERVICE/v3/api-docs
        name: CLIENT Service
        display-name: CLIENT Service
      - url: /CONTRACT-SERVICE/v3/api-docs
        name: CONTRACT Service
        display-name: CONTRACT Service
      - url: /AUTH-SERVICE/v3/api-docs
        name: Auth Service
        display-name: Auth Service
      - url: /LOAN-SERVICE/v3/api-docs
        name: LOAN SERVICE
        display-name: LOAN SERVICE
      - url: /ACCOUNT-SERVICE/v3/api-docs
        name: ACCOUNT SERVICE
        display-name: ACCOUNT SERVICE

